# configure updates globally
# default: all
# allowed: all, insecure, False
update: insecure

# set the default branch
# default: empty, the default branch on GitHub
branch: master

schedule: "every weeks on monday"

requirements:
  - requirements/staging.txt:
      update: all
      pin: True
  - requirements/local.txt:
      update: False
  - requirements/production.txt:
      update: insecure