language: python
python:
  - "3.7.7"
dist: bionic
branches:
  only:
    - master
services:
  - postgresql
before_install:
  - curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
  - sudo apt-get install nodejs -y -q
  - pip install -U pip
install:
  - pip install -r requirements/local.txt
  - pip install flake8
before_script:
  - psql -c 'create database dugong;' -U postgres
  - export DJANGO_SETTINGS_MODULE=dugong.settings.stage
  - mv env.example .env
script:
  - export CACHE_PATH=/tmp/cache
  - export SESSION_PATH=/tmp/
  - python manage.py frontend install
  - python manage.py frontend dev
  - python manage.py test --parallel
after_success:
  - pip install python-coveralls
  - coveralls

